import contextvars
from typing import Optional

# Queue for frontend DOM actions generated by the agent during a session
action_queue_var = contextvars.ContextVar("action_queue", default=None)

# Store for the current frontend state (e.g. expressions)
frontend_state_var = contextvars.ContextVar("frontend_state", default=None)

def get_plotted_expressions() -> str:
    """
    Returns a list of all currently plotted mathematical expressions on the user's graph sidebar.
    This lets you inspect the canvas (what is currently visible and what variables/functions exist).
    """
    expressions = frontend_state_var.get([])
    if not expressions:
        return "No expressions are currently plotted."
    
    formatted = []
    for exp in expressions:
        status = "visible" if exp.get("visible", True) else "hidden"
        formatted.append(f"- ID {exp.get('id', '?')}: {exp.get('latex', '')} (Color: {exp.get('color', '#2d70b3')}, {status})")
    
    return "Currently plotted expressions:\n" + "\n".join(formatted)

def plot_expression(latex_expression: str, color: Optional[str] = None) -> str:
    """
    Plots a mathematical expression, equation, function, or constant on the graph sidebar.
    Returns a success message upon queueing the action for the frontend.
    
    Args:
        latex_expression: The LaTeX string representation to plot (e.g., 'y=x^2', 'a=5', 'x=2', '\\sin(x)').
        color: Optional CSS color string (e.g. '#ff0000', 'red', 'hsl(210, 100%, 50%)'). If not provided, a color is chosen automatically.
    """
    queue = action_queue_var.get()
    if queue is not None:
        action = {
            "action": "addExpr",
            "latex": latex_expression
        }
        if color:
            action["color"] = color
        queue.put_nowait(action)
    return f"Successfully queued plot request for '{latex_expression}'. Inform the user."

def remove_expression(target_id: str) -> str:
    """
    Removes a plotted expression from the graph.
    
    Args:
        target_id: The exact ID of the expression to remove, which you can find by calling `get_plotted_expressions`.
    """
    queue = action_queue_var.get()
    if queue is not None:
        queue.put_nowait({
            "action": "removeExpr",
            "latex": target_id
        })
    return f"Successfully queued removal for {target_id}."

def update_slider_bounds(variable: str, min_val: str, max_val: str, step: str) -> str:
    """
    Updates the bounds of a slider for a variable that has already been plotted.
    Note: you usually need to plot the variable first using plot_expression (e.g., plot_expression('a=5')).
    
    Args:
        variable: The variable name exactly as defined (e.g., 'a', 'k')
        min_val: Minimum bound for the slider (e.g., '-10')
        max_val: Maximum bound for the slider (e.g., '10')
        step: Step size for the slider (e.g., '0.1')
    """
    queue = action_queue_var.get()
    if queue is not None:
        queue.put_nowait({
            "action": "updateSliderBounds",
            "variable": variable,
            "min": min_val,
            "max": max_val,
            "step": step
        })
    return f"Successfully queued slider bound update for {variable}."

def clear_all_expressions() -> str:
    """
    Clears all plotted expressions from the graph canvas.
    """
    expressions = frontend_state_var.get([])
    queue = action_queue_var.get()
    if queue is not None:
        for exp in expressions:
            queue.put_nowait({
                "action": "removeExpr",
                "latex": exp.get("id", "")
            })
    return "Successfully cleared all expressions."

def bulk_configure_graph(
    clear_first: bool = False, 
    plots: Optional[list[dict]] = None, 
    slider_bounds: Optional[list[dict]] = None,
    removes: Optional[list[str]] = None
) -> str:
    """
    POWERFUL bulk configuration tool that can do multiple actions at once.
    Use this to guarantee that all your plots and sliders are submitted together.

    Args:
        clear_first: Set to True to clear all existing expressions before drawing new ones.
        plots: List of dictionaries to plot. Each dict must have a "latex" key (string) and optionally a "color" key (string). 
               Example: [{"latex": "y = \\sin(x)", "color": "blue"}, {"latex": "a = 1", "color": "red"}]
        slider_bounds: List of dictionaries to configure sliders. Each dict must have "variable" (str), "min" (str), "max" (str), "step" (str).
               Example: [{"variable": "a", "min": "-5", "max": "5", "step": "0.1"}]
        removes: List of precise string IDs to selectively remove specific expressions without clearing everything.
    """
    queue = action_queue_var.get()
    if queue is not None:
        if clear_first:
            expressions = frontend_state_var.get([])
            for exp in expressions:
                queue.put_nowait({"action": "removeExpr", "latex": exp.get("id", "")})
        
        if removes:
            for target_id in removes:
                queue.put_nowait({"action": "removeExpr", "latex": target_id})
        
        if plots:
            for p in plots:
                action = {"action": "addExpr", "latex": p.get("latex", "")}
                if p.get("color"):
                    action["color"] = p.get("color")
                queue.put_nowait(action)
                
        if slider_bounds:
            for s in slider_bounds:
                queue.put_nowait({
                    "action": "updateSliderBounds",
                    "variable": s.get("variable", ""),
                    "min": s.get("min", "-10"),
                    "max": s.get("max", "10"),
                    "step": s.get("step", "0.1")
                })
    return "Successfully configured the graph with all requested updates."

sidebar_mcp_tools = [get_plotted_expressions, plot_expression, remove_expression, update_slider_bounds, clear_all_expressions, bulk_configure_graph]
