# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"$\n\x0e\x41nalyzeRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"\x85\x01\n\x0f\x41nalyzeResponse\x12\x14\n\x0c\x64omain_range\x18\x01 \x01(\t\x12\x19\n\x11\x66unction_analysis\x18\x02 \x01(\t\x12\x17\n\x0fsequence_series\x18\x03 \x01(\t\x12\x11\n\thas_error\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t2a\n\x11\x43\x61lculatorService\x12L\n\x0f\x41nalyzeFunction\x12\x1a.calculator.AnalyzeRequest\x1a\x1b.calculator.AnalyzeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=32
  _globals['_ANALYZEREQUEST']._serialized_end=68
  _globals['_ANALYZERESPONSE']._serialized_start=71
  _globals['_ANALYZERESPONSE']._serialized_end=204
  _globals['_CALCULATORSERVICE']._serialized_start=206
  _globals['_CALCULATORSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
