[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "grpcio>=1.80.0",
    "grpcio-tools>=1.80.0",
    "maturin>=1.11.5",
    "numpy>=2.4.1",
    "ruff>=0.15.7",
    "scipy>=1.17.0",
    "sympy>=1.14.0",
]

[tool.maturin]
manifest-path = "fast_math_rs/Cargo.toml"
features = ["pyo3/extension-module"]
module-name = "fast_math_rs"
